
version: '3.8'
services:
  db:
    image: postgres
    restart: always
    container_name: postgresdb-util-test
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - '5435:5435'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
